# Site settings
title: ILLSA
subtitle: International Language and Linguistics Students' Association
email: presidency.illsa@gmail.com
description: International Language and Linguistics Students' Association
baseurl: "/" # the subpath of your site, e.g. /blog
url: https://illsa.github.io # the base hostname & protocol for your site
author:
street_address: Kiki Street
city: Bouba Town
state: 
zip_code: 
country: Polyglot Land
phone: 00-888-SYNSEM

# Social settings
500px_url:
facebook_url: https://www.facebook.com/illsaorg
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: https://www.instagram.com/illsaorg/
linkedin_url: https://www.linkedin.com/company/illsa-international-language-and-linguistics-students-association/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/ILLSAorg

# Build settings
markdown: kramdown
